import type { TimbreName } from './types';

export interface SecondaryVoiceDefinition {
  waveform: 'sine' | 'same';
  frequencyRatio: number;
  detuneCents: number;
  gain: number;
}

export interface NoiseTextureDefinition {
  filterType: 'lowpass' | 'bandpass' | 'highpass';
  filterFrequency: number;
  resonance: number;
  gain: number;
}

export interface FrequencyModulationDefinition {
  frequencyRatio: number;
  depthCents: number;
}

export interface InstrumentDefinition {
  value: TimbreName;
  label: string;
  description: string;
  harmonics: readonly number[] | null;
  carrierGain: number;
  filterType: 'lowpass' | 'bandpass' | 'highpass';
  filterBaseFrequency: number;
  filterTracking: number;
  resonance: number;
  gainCompensation: number;
  articulation: 'sustained' | 'struck';
  attackSeconds: number;
  decaySeconds: number;
  vibratoRate: number;
  vibratoDepthCents: number;
  pitchDropCents: number;
  pitchDropSeconds: number;
  secondaryVoice: SecondaryVoiceDefinition | null;
  noiseTexture: NoiseTextureDefinition | null;
  frequencyModulation: FrequencyModulationDefinition | null;
}

export const INSTRUMENTS: Record<TimbreName, InstrumentDefinition> = {
  pure: {
    value: 'pure',
    label: 'Pure sine tone',
    description:
      'A plain sine wave with very few overtones. Useful as a neutral reference.',
    harmonics: null,
    carrierGain: 1,
    filterType: 'lowpass',
    filterBaseFrequency: 9000,
    filterTracking: 0,
    resonance: 0.1,
    gainCompensation: 1,
    articulation: 'sustained',
    attackSeconds: 0.006,
    decaySeconds: 0,
    vibratoRate: 0,
    vibratoDepthCents: 0,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: null,
    noiseTexture: null,
    frequencyModulation: null,
  },
  warm: {
    value: 'warm',
    label: 'Warm organ',
    description: 'Heavy organ drawbars with a deep octave underneath.',
    harmonics: [0, 1, 0.8, 0.15, 0.62, 0.1, 0.42, 0.08, 0.26],
    carrierGain: 0.8,
    filterType: 'lowpass',
    filterBaseFrequency: 350,
    filterTracking: 1.3,
    resonance: 0.7,
    gainCompensation: 1,
    articulation: 'sustained',
    attackSeconds: 0.032,
    decaySeconds: 0,
    vibratoRate: 0,
    vibratoDepthCents: 0,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'sine',
      frequencyRatio: 0.5,
      detuneCents: 0,
      gain: 0.58,
    },
    noiseTexture: null,
    frequencyModulation: null,
  },
  reed: {
    value: 'reed',
    label: 'Clarinet-like reed',
    description: 'A pinched, nasal reed with forceful odd harmonics.',
    harmonics: [0, 1, 0, 0.92, 0, 0.62, 0, 0.4, 0, 0.25],
    carrierGain: 0.88,
    filterType: 'bandpass',
    filterBaseFrequency: 350,
    filterTracking: 1.2,
    resonance: 6,
    gainCompensation: 1.05,
    articulation: 'sustained',
    attackSeconds: 0.018,
    decaySeconds: 0,
    vibratoRate: 6.2,
    vibratoDepthCents: 28,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: null,
    noiseTexture: null,
    frequencyModulation: null,
  },
  bright: {
    value: 'bright',
    label: 'Bright synthesiser',
    description: 'A sharp electronic buzz with plenty of high harmonics.',
    harmonics: [0, 1, 0.9, 0.72, 0.58, 0.48, 0.4, 0.34, 0.29, 0.25, 0.22, 0.19],
    carrierGain: 0.75,
    filterType: 'highpass',
    filterBaseFrequency: 500,
    filterTracking: 0.5,
    resonance: 0.8,
    gainCompensation: 0.62,
    articulation: 'sustained',
    attackSeconds: 0.004,
    decaySeconds: 0,
    vibratoRate: 0,
    vibratoDepthCents: 0,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'same',
      frequencyRatio: 2,
      detuneCents: 0,
      gain: 0.35,
    },
    noiseTexture: null,
    frequencyModulation: null,
  },
  hollow: {
    value: 'hollow',
    label: 'Hollow',
    description: 'A cavernous, low-passed tone with a dominant sub-octave.',
    harmonics: [0, 1, 0, -0.6, 0, 0.32, 0, -0.18, 0, 0.1],
    carrierGain: 0.75,
    filterType: 'lowpass',
    filterBaseFrequency: 260,
    filterTracking: 0.75,
    resonance: 2,
    gainCompensation: 0.82,
    articulation: 'sustained',
    attackSeconds: 0.08,
    decaySeconds: 0,
    vibratoRate: 2,
    vibratoDepthCents: 12,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'sine',
      frequencyRatio: 0.5,
      detuneCents: 0,
      gain: 0.7,
    },
    noiseTexture: null,
    frequencyModulation: null,
  },
  flute: {
    value: 'flute',
    label: 'Flute-like',
    description:
      'A faint whistle wrapped in an exaggerated stream of breath noise.',
    harmonics: [0, 1, 0.035, 0.018, 0.006, 0.003],
    carrierGain: 0.55,
    filterType: 'lowpass',
    filterBaseFrequency: 1500,
    filterTracking: 4.5,
    resonance: 0.35,
    gainCompensation: 1,
    articulation: 'sustained',
    attackSeconds: 0.12,
    decaySeconds: 0,
    vibratoRate: 5.4,
    vibratoDepthCents: 25,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: null,
    noiseTexture: {
      filterType: 'highpass',
      filterFrequency: 2500,
      resonance: 0.35,
      gain: 0.12,
    },
    frequencyModulation: null,
  },
  trumpet: {
    value: 'trumpet',
    label: 'Trumpet-like brass',
    description: 'A bold brass buzz with a focused mid-range and quick attack.',
    harmonics: [0, 1, 0.95, 0.82, 0.7, 0.58, 0.48, 0.4, 0.32, 0.25, 0.18],
    carrierGain: 0.8,
    filterType: 'bandpass',
    filterBaseFrequency: 700,
    filterTracking: 3.8,
    resonance: 2.5,
    gainCompensation: 0.7,
    articulation: 'sustained',
    attackSeconds: 0.012,
    decaySeconds: 0,
    vibratoRate: 5.8,
    vibratoDepthCents: 35,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'same',
      frequencyRatio: 0.5,
      detuneCents: 0,
      gain: 0.18,
    },
    noiseTexture: {
      filterType: 'bandpass',
      filterFrequency: 1800,
      resonance: 0.8,
      gain: 0.03,
    },
    frequencyModulation: null,
  },
  strings: {
    value: 'strings',
    label: 'Bowed-string-like',
    description: 'A rough, chorused bow with a slow swell and wide vibrato.',
    harmonics: [0, 1, 0.65, 0.5, 0.4, 0.33, 0.28, 0.24, 0.2, 0.17, 0.14],
    carrierGain: 0.65,
    filterType: 'lowpass',
    filterBaseFrequency: 700,
    filterTracking: 3.5,
    resonance: 0.9,
    gainCompensation: 0.65,
    articulation: 'sustained',
    attackSeconds: 0.18,
    decaySeconds: 0,
    vibratoRate: 5,
    vibratoDepthCents: 42,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'same',
      frequencyRatio: 1,
      detuneCents: 24,
      gain: 0.7,
    },
    noiseTexture: {
      filterType: 'bandpass',
      filterFrequency: 1400,
      resonance: 0.7,
      gain: 0.06,
    },
    frequencyModulation: null,
  },
  mallet: {
    value: 'mallet',
    label: 'Mallet-like',
    description: 'A hard, bell-like strike with an uneven metallic spectrum.',
    harmonics: [0, 1, 0, 0.62, 0, 0.08, 0.4, 0, 0.2, 0, 0.12],
    carrierGain: 0.7,
    filterType: 'bandpass',
    filterBaseFrequency: 1000,
    filterTracking: 6,
    resonance: 4.8,
    gainCompensation: 0.9,
    articulation: 'struck',
    attackSeconds: 0.002,
    decaySeconds: 0.42,
    vibratoRate: 0,
    vibratoDepthCents: 0,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'sine',
      frequencyRatio: 2.71,
      detuneCents: 0,
      gain: 0.6,
    },
    noiseTexture: null,
    frequencyModulation: {
      frequencyRatio: 3.73,
      depthCents: 340,
    },
  },
  drum: {
    value: 'drum',
    label: 'Pitched drum',
    description: 'A short tom-like thump with a fast downward pitch bend.',
    harmonics: [0, 1, 0.7, 0.22, 0.08, 0.03],
    carrierGain: 0.75,
    filterType: 'bandpass',
    filterBaseFrequency: 160,
    filterTracking: 1.7,
    resonance: 6.5,
    gainCompensation: 1.05,
    articulation: 'struck',
    attackSeconds: 0.002,
    decaySeconds: 0.16,
    vibratoRate: 0,
    vibratoDepthCents: 0,
    pitchDropCents: 1100,
    pitchDropSeconds: 0.1,
    secondaryVoice: {
      waveform: 'sine',
      frequencyRatio: 0.5,
      detuneCents: 0,
      gain: 0.7,
    },
    noiseTexture: {
      filterType: 'bandpass',
      filterFrequency: 900,
      resonance: 1.2,
      gain: 0.22,
    },
    frequencyModulation: null,
  },
  'sub-bass': {
    value: 'sub-bass',
    label: 'Deep sub pulse',
    description:
      'A deliberately oversized low rumble two octaves below the note.',
    harmonics: [0, 1, 0.1, 0.03],
    carrierGain: 0.65,
    filterType: 'lowpass',
    filterBaseFrequency: 120,
    filterTracking: 0.7,
    resonance: 3,
    gainCompensation: 0.72,
    articulation: 'sustained',
    attackSeconds: 0.025,
    decaySeconds: 0,
    vibratoRate: 1.5,
    vibratoDepthCents: 45,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'sine',
      frequencyRatio: 0.25,
      detuneCents: 0,
      gain: 0.75,
    },
    noiseTexture: null,
    frequencyModulation: null,
  },
  arcade: {
    value: 'arcade',
    label: 'Arcade square wave',
    description: 'An unapologetic retro square-wave beep with a hard edge.',
    harmonics: [0, 1, 0, 0.33, 0, 0.2, 0, 0.14, 0, 0.11, 0, 0.09],
    carrierGain: 0.9,
    filterType: 'highpass',
    filterBaseFrequency: 300,
    filterTracking: 0.3,
    resonance: 0.4,
    gainCompensation: 0.68,
    articulation: 'sustained',
    attackSeconds: 0.002,
    decaySeconds: 0,
    vibratoRate: 0,
    vibratoDepthCents: 0,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'same',
      frequencyRatio: 2,
      detuneCents: 0,
      gain: 0.28,
    },
    noiseTexture: null,
    frequencyModulation: null,
  },
  'air-jet': {
    value: 'air-jet',
    label: 'Air-jet whistle',
    description:
      'A thin whistle almost buried inside a loud stream of filtered air.',
    harmonics: null,
    carrierGain: 0.14,
    filterType: 'lowpass',
    filterBaseFrequency: 8000,
    filterTracking: 0,
    resonance: 0.1,
    gainCompensation: 0.85,
    articulation: 'sustained',
    attackSeconds: 0.14,
    decaySeconds: 0,
    vibratoRate: 7.3,
    vibratoDepthCents: 60,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: null,
    noiseTexture: {
      filterType: 'bandpass',
      filterFrequency: 4200,
      resonance: 2,
      gain: 0.3,
    },
    frequencyModulation: null,
  },
  siren: {
    value: 'siren',
    label: 'Alarm siren',
    description:
      'An exaggerated alarm wobble that swings sharply around the pitch.',
    harmonics: null,
    carrierGain: 0.9,
    filterType: 'lowpass',
    filterBaseFrequency: 6500,
    filterTracking: 0,
    resonance: 0.3,
    gainCompensation: 0.78,
    articulation: 'sustained',
    attackSeconds: 0.008,
    decaySeconds: 0,
    vibratoRate: 4.2,
    vibratoDepthCents: 360,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'sine',
      frequencyRatio: 1.5,
      detuneCents: 0,
      gain: 0.15,
    },
    noiseTexture: null,
    frequencyModulation: null,
  },
  robot: {
    value: 'robot',
    label: 'Robot FM growl',
    description:
      'A harsh, clangorous robot voice with non-integer frequency modulation.',
    harmonics: [0, 1, 0.44, 0.22, 0.12, 0.08],
    carrierGain: 0.7,
    filterType: 'bandpass',
    filterBaseFrequency: 300,
    filterTracking: 2.2,
    resonance: 3.5,
    gainCompensation: 0.65,
    articulation: 'sustained',
    attackSeconds: 0.008,
    decaySeconds: 0,
    vibratoRate: 0,
    vibratoDepthCents: 0,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'sine',
      frequencyRatio: 0.5,
      detuneCents: 0,
      gain: 0.25,
    },
    noiseTexture: null,
    frequencyModulation: {
      frequencyRatio: 1.414,
      depthCents: 480,
    },
  },
  pluck: {
    value: 'pluck',
    label: 'Sharp plucked string',
    description: 'A dry, bright twang with a noisy pick and an abrupt decay.',
    harmonics: [0, 1, 0.85, 0.65, 0.4, 0.25, 0.15],
    carrierGain: 0.85,
    filterType: 'lowpass',
    filterBaseFrequency: 500,
    filterTracking: 5,
    resonance: 1,
    gainCompensation: 0.75,
    articulation: 'struck',
    attackSeconds: 0.001,
    decaySeconds: 0.28,
    vibratoRate: 0,
    vibratoDepthCents: 0,
    pitchDropCents: 0,
    pitchDropSeconds: 0,
    secondaryVoice: {
      waveform: 'sine',
      frequencyRatio: 2,
      detuneCents: 0,
      gain: 0.15,
    },
    noiseTexture: {
      filterType: 'highpass',
      filterFrequency: 3000,
      resonance: 0.5,
      gain: 0.09,
    },
    frequencyModulation: null,
  },
};

export const INSTRUMENT_OPTIONS = Object.values(INSTRUMENTS);

export function instrumentFilterFrequency(
  definition: InstrumentDefinition,
  fundamental: number,
): number {
  const trackedFrequency =
    definition.filterBaseFrequency +
    Math.max(0, fundamental) * definition.filterTracking;
  return Math.min(12_000, Math.max(80, trackedFrequency));
}
